### ISSUE TITLE
how to select mode 

### ISSUE THREAD

**Issue by Ritesh1991** [xavierpuigf/ProgramDataCollection#1]
Hi thanks for making this tool. I want use this tool for my research work. Can you help me how to select mode in this tool?

As below mention in readme file.
Open interface.html in a browser as:

interface.html?filetasks={CONTENT}&mode={MODE}
Where {MODE} is the mode of annotation
How to select MODE of annotation here 

Thanks

**Comment by xavierpuigf** [comment]
Hi, you just need to introduce one of the options that appear on the readme. For instance, if you want to create a single task called `example_task` you can just open the following url:

interface.html?filetasks=example_task&mode=TASK_NAME

As the readme indicates, you have 4 possible modes, based on which the filetasks field will have a different meaning.

**Comment by Ritesh1991** [comment]
Thank you for your prompt reply sir 

Ohh Now it worked now. It give some error Clouser library but i solved it by just copying Clouser library in ProgramDatacollection folder.
Thanks again

**Comment by xavierpuigf** [comment]
Glad it worked! Closing the issue
